name: Build & Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
 
permissions:
  contents: write
  pages:    write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Code
      - name: Checkout code
        uses: actions/checkout@v4
        
      # 2) Node avec cache
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      # 4) Cache Hugo resources (CRITIQUE pour tes 948 images)
      - name: Cache Hugo resources
        uses: actions/cache@v3
        with:
          path: |
            resources/_gen
            public
            .hugo_build.lock
          key: hugo-cache-${{ hashFiles('assets/**', 'content/**', 'data/**', 'layouts/**') }}
          restore-keys: |
            hugo-cache-
            
      # 5) Dépendances npm
      - name: Install dependencies
        run: npm ci
        
      # 6) Build CSS / JS
      - name: Build assets
        run: |
          npm run build:css
          npm run build:js
          
      # 7) Hugo Extended
      - name: Install Hugo Extended
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
          
      # 8) Build Hugo simple et efficace
      - name: Build site
        run: |
          echo "🚀 Building Hugo site..."
          hugo --gc --minify
          echo "✅ Build complete!"
          
      # 9) Déploiement
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true
